server:
  port: 8080

spring:
  application:
    name: backend
  profiles:
    active: local
  jwt:
    access-token-expiration: 3600000
    refresh-token-expiration: 1209600000
    secret: ${JWT_SECRET:}
  social:
    apple:
      audience: com.fitally.app

