server:
  port: 8080

spring:
  application:
    name: backend

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "this-is-a-very-long-key-for-fitally-jwt-token-example-1234567890"
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000